### ISSUE TITLE
Welcome page design

### ISSUE THREAD

**Issue by atinux** [nuxt/ui-templates#11]
![Welcome page.png](https://volta.s3.fr-par.scw.cloud/Welcome_page_6071e3500b.png)

**Comment by atinux** [comment]
@R-mooon can you share the design resources (icons and colors) needed for integrating it?

@danielroe would you mind implementing it? Also would love some insights from @pi0 how to best implement it :grinning:

Also related to #1

**Comment by pi0** [comment]
Nice work! Added #14 for prep for implementing. Having resources beforehand would be helpful :)

**Comment by R-mooon** [comment]
Cards bg : #E6F0F0
Card titles : #003543
Card descriptions : #255461
Bg "create and app.vue" : #D1E2E2
Default link : #497A87

[icons.zip](https://github.com/nuxt/design/files/6740920/icons.zip)

Also Figma file : https://www.figma.com/file/fny5IrHsmIc6ZWxR0di4mO/?node-id=60%3A0

**Comment by flozero** [comment]
If you need help on the design side I can probably help @Atinux (just need to have access to figma)

**Comment by atinux** [comment]
@R-mooon can you share the link to it?

**Comment by flozero** [comment]
Also @R-mooon the nuxt svg is missing in the icons.zip

**Comment by flozero** [comment]
Not so far from the image ^^. Will create a pr until I can have access to have a pixel and color perfect

![Screen Shot 2021-10-20 at 2 39 22 PM](https://user-images.githubusercontent.com/11556276/138094322-919024ab-3906-44d4-8f70-0b7dd754dae2.png)

**Comment by pi0** [comment]
Thanks for helping @f3ltron. Of course PR is more than welcome! I will ask @R-mooon to provide public Figma links and missing icons to the repo (they should be in https://github.com/nuxt/design/tree/main/public/assets)

(also closing issue as welcome page is already implemented)

**Comment by flozero** [comment]
I don't think you should close it @pi0  The design as the new design is not implemented. I think it was the purpose of this issue

**Comment by pi0** [comment]
This is an old issue and no corresponding Figma design to review. Let's create a new one and track there once design was ready :)
