### ISSUE TITLE
A small CSS fix

### ISSUE THREAD

**Issue by liconver** [nuxt/ui-templates#116]
Hello, this may be a bit trivial but I noticed on the welcome page that inside the third <a> element, the twitter one, the text doesn't quite line up with the previous two anchor tags ( [https://templates.ui.nuxtjs.org/templates/welcome](url) )

I looked and the CSS classes are a little bit different on that one so I was thinking I could just make them all uniform.

But also with that being done all 3 <a> elements would be the same and you could use "v-for" and then populate their individual data from an array perhaps, like you did with the {{messages}} text.

I've never contributed to a project like this before would this be something I could do a pull request for?

**Comment by danielroe** [comment]
Absolutely! Though note that the templates are not written in Vue (though they are compiled to it), so `v-for` won't exactly work.

**Comment by liconver** [comment]
Ok, cool.  Yeah on this repo the templates are HTML files but I noticed in the @nuxt/ui-templates npm module that downloads with nuxi init they are in .Vue files which I assume is what the project builds from.
