### ISSUE TITLE
I have such doubts.

### ISSUE THREAD

**Issue by HomWang** [nuxt/ui-templates#135]
I don't know whether the expectation of this project will be the same as that of element UI. There will be more possibilities. And for all users. I have such doubts.

**Comment by atinux** [comment]
At the moment we use it internally for our examples like described on https://github.com/nuxt/ui/tree/main/packages/ui

**Comment by antfu** [comment]
> same as that of element UI

That would probably out-of-scope. We are more intended to use it as a standard UI design for our internal tools. We might consider going beyond that in the future but can't make any promises right now. Thanks for bringing this up.
