### ISSUE TITLE
Production bundles

### ISSUE THREAD

**Issue by danielroe** [nuxt/ui-templates#15]
Random idea, but what do you think about producing production bundles that are fully JS for pnp support? cc: @pi0 

```ts
import template from '@nuxt/design/404'
import messages from '@nuxt/design/messages/en'
// possibly even for static assets?
import vfs from '@nuxt/design/assets'

const html = template(messages)
```

**Comment by pi0** [comment]
This is the purpose of this project. Yes, we should publish npm package :) Importing would be from `/dist/` unless using exports map.

Regarding messages, they are _mock_, not final messages.

**Comment by danielroe** [comment]
I think we can start using exports maps and omit `dist` given target usage of this package.
