### ISSUE TITLE
New loading screen performs extremely bad

### ISSUE THREAD

**Issue by P4sca1** [nuxt/ui-templates#174]
Using Safari 16.1 on MacOS.
CPU Usage is at **up to 250%** while the page is displayed.

https://user-images.githubusercontent.com/10992664/195350670-f4d8b465-f396-4dc6-8322-d01757641bed.mov

**Comment by danielroe** [comment]
you can disable the animation by hovering over the top right corner and clicking.

see https://github.com/nuxt/ui/issues/159

**Comment by P4sca1** [comment]
Just tested it and CPU Usage is still > 220%, even without the cursor based animation showing (the animation at the bottom still plays).

**Comment by P4sca1** [comment]
It works without such performance impacts on Google Chrome. However this does not seem to be related only to Safari, because in #159 the used operation system was Linux.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Just tried on Safari with my M1 Max - yeah the performance is really bad and the visual is also buggy. I belive there might be some performance issue with WebKit. Made #175 to improve that and disabled the animation in Safari by default.
