### ISSUE TITLE
Exception on Components Demo

### ISSUE THREAD

**Issue by c0nst4ntin** [nuxt/ui-templates#188]
**When trying to access https://components.ui.nuxtjs.org/ I get an Error:**

> This Serverless Function has crashed.

> Your connection is working correctly.

> Vercel is working correctly.

**Screenshot:** <br>
<img width="531" alt="error-page" src="https://user-images.githubusercontent.com/27086157/206186764-b3161048-2d8f-42c0-a103-f88254b32749.png">

**Comment by IcanPressF** [comment]
nuxt ui is dead
