### ISSUE TITLE
Build System and Packaging

### ISSUE THREAD

**Issue by pi0** [nuxt/ui-templates#2]
As of now, we use vanilla inlined css and svg inside error templates (with duplicates), poi for loading-screen and a mixed design for [youch](https://github.com/nuxt/youch).

Desired output from nice is a set of html templates (lodash template), compiled styles and minimal runtime scripts.

I had been looking into [parcel](https://parceljs.org) and [posthtml](https://github.com/posthtml/posthtml) since it seems a perfect stack for building such output. Parcel would make bundling a template much easier and built-in posthtml support brings 
 opportunities like template support, easy development and inlining assets which is far easier than alternatives like rollup or webpack or vanilla if we want to use...

Only issue i couldn't resolve was that posthtml seems to be prod only. So we might find a way to enable it in development of parcel or use with programmatic API...

**Comment by atinux** [comment]
Update from [last commit](https://github.com/nuxt/nice/commit/6237cd22a29e8a125a91816ff87b2180f74f3137), we are using H2 to proxy to Parcel and use [Edge.js](https://edge.adonisjs.com) for templating engine.

We still need to have the `build` script to inline all assets for production (css and svg).

**Comment by pi0** [comment]
Migrated to vite
