### ISSUE TITLE
Serving Assets

### ISSUE THREAD

**Issue by pi0** [nuxt/ui-templates#3]
For nuxt 2 we don't have any issues but also not have much opportunities to have a more complex and beautiful design because of size and single file limitation and it is somehow tricky for loading-screen as we need a whole conntect stack to serve static assets.

One solution to this would be serving assets from a CDN (like jsdelivr) including js libraries we use. This could make development and distribution much easier since final templates are html/string only can be embeded into any bundle also in production

**Comment by atinux** [comment]
About CND, in development I work offline (in a plane), it should be nice to serve the assets with a server middleware.

**Comment by atinux** [comment]
What about having a `static/` directory that we could give to Nuxt 3 as a multi-app, this way it could work for both SSR & static generation (`.output/public`).

**Comment by pi0** [comment]
Currently, we inline assets and also distribute other files with `@nuxt/design` project (which could be served by jsdelivr if needed)
