### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by pi0** [nuxt/ui-templates#4]
We need to choose a CSS design system for nice project. I'm aware of nuxt/ui development, and it would be also totally perfect to adopt it just need to ensure it won't block project development and also we have a way to extract/inline and use css to redistribute (i think it was using css-in-js within vue components but not sure about latest state)

Other alternatives are in-house designs with or without tailwind css. What matters in the end is that we can distribute or inline stylesheets.

/cc @Atinux @alexchopin

**Comment by atinux** [comment]
Nuxt UI is a TailwindCSS plugin, so we should setup Tailwind with the Nuxt UI plugin and generate the CSS file that Parcel will inline in the HTML.

**Comment by atinux** [comment]
Waiting for @nuxt/ui plugin for Tailwind.

**Comment by flozero** [comment]
Does it mean nuxt ui will transform the default templates existing inside templates folder ? or it will be keep as index.html with "vanilla html "

**Comment by pi0** [comment]
@f3ltron We will likely expose tailwind config and a set of base Vue components to use for devtools project. Basically more data exported from `@nuxt/deisign` package :)

**Comment by flozero** [comment]
Make sense will wait for more infos on what to do then :)
