### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pi0** [nuxt/ui-templates#5]
Internationalization of messages would be important specially for production error pages.

We currently maintain them as a config: https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/config/messages.js

But could be nice if we export translated messages to be set with single config

**Comment by atinux** [comment]
Detecting the language for error page can happen by checking the headers in development + explain to set the defaultLanguage for `nuxt/nice`.

**Comment by atinux** [comment]
I started to use `data/en/` to store english messages.

**Comment by pi0** [comment]
Moving to https://github.com/nuxt/translations
